Revert "devel/strace: fix build on mpc85xx target"
This reverts commit 519a199cbcc0930e229ddd7087309326a846bdce.

Multiple users have reported building failures on ARM architectures, e.g.:

    In file included from defs.h:42:0,
                     from process.c:37:
    process.c:51:22: error: 'struct user_regs' has no member named 'ARM_r0'
     #define uoff(member) offsetof(struct user, member)
                          ^
    ./linux/arm/userent.h:1:3: note: in expansion of macro 'uoff'
     { uoff(regs.ARM_r0), "r0" },
       ^

Signed-off-by: Jo-Philipp Wich <jo@mein.io>